apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: {{.AppName}}
  description: {{.Description}}
  owner: {{.TeamName}}
spec:
  type: library
  lifecycle: production
  owner: {{.TeamName}}
  system: Clever
